version: '3.7'

x-env-vars: &env-vars
  POSTGRES_HOST: ${POSTGRES_HOST:-db}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_USER: ${POSTGRES_USER:-db_user}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
  POSTGRES_DB: ${POSTGRES_DB:-db}

services:
  app:
    image: app:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      <<: *env-vars
    command: bash -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      <<: *env-vars
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
